### ISSUE TITLE
loading websocket module...

### ISSUE THREAD

**Issue by mateusmirandaalmeida** [edgardmessias/whatsapp-protocol-log#1]
After running the project, it gets stuck in "loading websocket module..."

**Comment by edgardmessias** [comment]
Olá Mateus, moro pertinho de você em Maringá.
Tente atualizar os pacotes do NPM que provavelmente irá funcionar bem, preciso atualizar aqui também.

**Comment by edgardmessias** [comment]
Resolved with 6b0b87f9a767ba01e0ac194dabec0f0c25f191ca
